### ISSUE TITLE
Add support for the cusparseSgemmi API

### ISSUE THREAD

**Issue by paravoid** [ROCmSoftwarePlatform/hipSPARSE#120]
I was looking into what it would take to [Marian-NMT](https://marian-nmt.github.io/) to HIP (note: I am not affiliated with the project). Having gone through an initial hipification, I stumbled into a function call to `cusparseSgemmi`, which does not seem to be supported by hipSPARSE/rocSPARSE as far as I can tell from the [documentation](https://github.com/ROCm-Developer-Tools/HIP/blob/master/docs/markdown/CUSPARSE_API_supported_by_HIP.md) and source code.

Is this something that happens to be in your roadmap? Thanks for all of your efforts!

**Comment by ntrost57** [comment]
Yes, this is something on our roadmap and will be added in one of our future releases.

**Comment by paravoid** [comment]
Hey, saw the bug was closed! Was this implemented already? Is the code available in some branch somewhere?

**Comment by ntrost57** [comment]
It has been added to develop branch with PR #125
