### ISSUE TITLE
[bug] deps/convert: Unable to execute binary file

### ISSUE THREAD

**Issue by nmanhong** [ROCmSoftwarePlatform/hipSPARSE#184]
When I was in cmake, it prompted "-- Downloading and extracting test matrix SNAP/amazon0312.tar.gz
/home/loongson/ROCm/rocSPARSE/deps/convert: /home/loongson/ROCm/rocSPARSE/deps/convert:
Unable to execute binary file".
My system is based on mips. It cannot execute this binary file, can you share it?
So I can compile it from source code by myself, this convert

**Comment by nmanhong** [comment]
@ntrost57

**Comment by ntrost57** [comment]
The source file is in the same directory `rocSPARSE/deps/convert.cpp`
