### ISSUE TITLE
Is hipSPARSE available on Windows ?

### ISSUE THREAD

**Issue by shock-pro** [ROCmSoftwarePlatform/hipSPARSE#195]
Hello Everyone,
Is hipSPARSE available on Windows ?
Thanks

**Comment by doctorcolinsmith** [comment]
hipSPARSE is not currently supported on Windows.

**Comment by shock-pro** [comment]
Thanks for this info!
Any plans to port hipSPARSE to Windows ?
I understand that AMD has dropped OpenCL support, 
what solutions are available for HPC on Windows with AMD cards ?
Thanks again!
