### ISSUE TITLE
Don't use find_package(HIP REQUIRED)

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/hipSPARSE#211]
This package uses [`find_package(HIP REQUIRED)`](https://github.com/ROCmSoftwarePlatform/hipSPARSE/blob/develop/cmake/Dependencies.cmake#L30).

There is both a module `FindHIP.cmake` and a `hip-config.cmake` file, it's ambiguous because search is case-insensitive, so please specify whether it's the module or the config file explicitly, like `find_package(HIP MODULE REQUIRED)` or `find_package(HIP REQUIRED CONFIG)`.

From the CMake docs:

> In Module mode, CMake searches for a file called Find<PackageName>.cmake. The file is first searched in the CMAKE_MODULE_PATH, then among the Find Modules provided by the CMake installation.

> If the MODULE option is not specified in the above signature, CMake first searches for the package using Module mode. Then, if the package is not found, it searches again using Config mode.

The Spack package manager sets `CMAKE_PREFIX_PATH` to the hip install prefix, but since this is only used only in Config mode, no module is found, so when it switches to Config mode it detects hip-config.cmake. (see https://github.com/spack/spack/pull/25264)

**Comment by ntrost57** [comment]
Thanks @haampie.
I have raised PR #212. Could you check if this fixes the issue with Spack that you are observing?
