### ISSUE TITLE
Build homogeneity for CMake options?

### ISSUE THREAD

**Issue by marcodelapierre** [ROCmSoftwarePlatform/hipSPARSE#218]
Both hipBLAS and hipSOLVER use "USE_CUDA=ON" to specify a CUDA backend build,
whereas hipSPARSE currently uses "BUILD_CUDA=ON".
(hipFFT uses yet another one)

It would probably ease installation efforts if the syntax could be made more homogeneous.

Thanks,

**Comment by ntrost57** [comment]
Closing as this has been solved.
