### ISSUE TITLE
Wrong hipsparseSpSV_solve argument

### ISSUE THREAD

**Issue by NamjaeChoi** [ROCmSoftwarePlatform/hipSPARSE#314]
`cusparseSpSV_solve` does not receive buffer as the last argument but `hipsparseSpSV_solve` does.
If this was not intentional, it should be fixed.

`cusparseSpSV_solve`
https://docs.nvidia.com/cuda/cusparse/#cusparsespsv

`hipsparseSpSV_solve`

```
hipsparseStatus_t hipsparseSpSV_solve(hipsparseHandle_t           handle,
                                      hipsparseOperation_t        opA,
                                      const void*                 alpha,
                                      const hipsparseSpMatDescr_t matA,
                                      const hipsparseDnVecDescr_t x,
                                      const hipsparseDnVecDescr_t y,
                                      hipDataType                 computeType,
                                      hipsparseSpSVAlg_t          alg,
                                      hipsparseSpSVDescr_t        spsvDescr,
                                      void*                       externalBuffer);
```

**Comment by YvanMokwinski** [comment]
It was intentional as we don't have the same API in rocSPARSE.
Why kind of issues do you have about it ?

**Comment by NamjaeChoi** [comment]
Not a significant issue. I was just a bit confused by a compile error while porting my CUDA code to HIP because it was not well documented. Other people may have the same confusion.

**Comment by YvanMokwinski** [comment]
That's something we could easily fix in hipSPARSE. 
Let me see, I'll get back to you.

**Comment by YvanMokwinski** [comment]
Fixed, thank you for bringing it up.
commit 68df770
