### ISSUE TITLE
unclear buffersize

### ISSUE THREAD

**Issue by jakub-homola** [ROCmSoftwarePlatform/hipSPARSE#323]
Hello,

[In the documentation](https://hipsparse.readthedocs.io/en/rocm-5.5.0/usermanual.html#hipsparsespsv-buffersize), in the generic API section, the `_buffersize` functions do not specify whether the buffer size is in bytes or in elements. Should I allocate `buffersize` or `buffersize * sizeof(double)` bytes of memory for the buffer?

Please clarify that in the docs.

**Comment by YvanMokwinski** [comment]
Hello Jakub,

If unspecified, the buffer size is a number of bytes. 
We will add a note.

Thank you
