### ISSUE TITLE
sddmm batch support issue

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipSPARSE#398]
It seems that a batch size larger than 1 produces incorrect results for sddmm:

https://github.com/zjin-lcf/HeCBench/tree/master/sddmm-batch-hip

To reproduce:

make
./main 2 4 4 4 9 1 1

Thanks

**Comment by YvanMokwinski** [comment]
batch calculation for rocsparse-sddmm are not yet supported, we will throw a proper error for now.
Thank you.

**Comment by jinz2014** [comment]
Could you please re-open the issue because it is not complete ?
